# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"atomwise_tokenizer": "00_SmilesPE.ipynb",
         "randomize_smiles": "00_SmilesPE.ipynb",
         "get_vocabulary": "00_SmilesPE.ipynb",
         "update_pair_statistics": "00_SmilesPE.ipynb",
         "get_pair_statistics": "00_SmilesPE.ipynb",
         "replace_pair": "00_SmilesPE.ipynb",
         "prune_stats": "00_SmilesPE.ipynb",
         "learn_SPE": "00_SmilesPE.ipynb",
         "SPE_Tokenizer": "00_SmilesPE.ipynb",
         "encode": "00_SmilesPE.ipynb",
         "isolate_glossary": "00_SmilesPE.ipynb"}

modules = ["SmilesPE.py"]

doc_url = "https://XinhaoLi74.github.io/SmilesPE/"

git_url = "https://github.com/XinhaoLi74/SMILES Pair Encoding/tree/master/"

def custom_doc_links(name): return None
